services:
  banco_dados:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://banco_dados:27017/carcara_db
    depends_on:
      - banco_dados
    command: npm run dev

  app:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mongo_data: